# Generated by Django 2.2.4 on 2019-08-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی ها'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cost',
            field=models.CharField(default='توافقی', max_length=100, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(verbose_name='متن آگهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان آگهی'),
        ),
    ]
