# Generated by Django 2.2.4 on 2019-08-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20190821_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
