# Generated by Django 2.2.4 on 2019-09-02 07:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20190821_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='engheza',
            field=models.IntegerField(default=0, help_text='تعداد روز را وارد کنید', verbose_name='مهلت آگهی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='enghezaDate',
            field=models.DateField(default=datetime.datetime(2019, 9, 2, 11, 55, 47, 291299), verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='publishDate',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
    ]
