# Generated by Django 2.2.4 on 2019-08-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(verbose_name='معرفی مختصر')),
                ('bodyType', models.CharField(choices=[('سدان', 'سدان'), ('هاچ بک', 'هاچ بک'), ('کوپه', 'کوپه'), ('وانت', 'وانت'), ('کراس اوور', 'کراس اوور')], max_length=100, verbose_name='نوع بدنه')),
                ('yearOfProduction', models.IntegerField(help_text='مثال: 2019', max_length=4, verbose_name='سال تولید')),
                ('engineVolume', models.IntegerField(help_text='حجم موتور برحسب سی سی', verbose_name='حجم موتور')),
                ('engineType', models.CharField(help_text='به طور مثال: چهار سیلندر خطی', max_length=100, verbose_name='نوع موتور')),
                ('cylinderNum', models.IntegerField(verbose_name='تعداد سیلندرها')),
                ('valveNum', models.IntegerField(verbose_name='تعداد سوپاپ ها')),
                ('tankCapacity', models.IntegerField(help_text='ظرفیت باک بنزین برحسب لیتر', verbose_name='ظرفیت باک ینزین')),
                ('maxPower', models.IntegerField(help_text='حداکثر توان خروجی برحسب اسب بخار', verbose_name='حداکثر توان خروجی')),
                ('maxTorque', models.IntegerField(help_text='حداکثر گشتاور برحسب دور بر دقیقه', verbose_name='حداکثر گشتاور')),
                ('gearboxType', models.CharField(choices=[('دستی', 'دستی'), ('اتوماتیک', 'اتوماتیک')], max_length=100, verbose_name='نوع جعبه دنده')),
                ('gearboxNum', models.IntegerField(verbose_name='تعداد دنده')),
                ('breakType', models.CharField(max_length=100, verbose_name='نوع سیستم ترمز')),
                ('maxSpeed', models.IntegerField(help_text='حداکثر سرعت برحسب کیلومتر بر ساعت', verbose_name='حداکثر سرعت')),
                ('zeroTOHundredAcceleration', models.DecimalField(decimal_places=1, help_text='شتاب 0 تا 100 برحسب ثانیه', max_digits=4, verbose_name='شتاب 0 تا 100')),
                ('cityFuelUse', models.DecimalField(decimal_places=1, help_text='مصرف سوخت شهری برحسب لیتر در هر صد کیلومتر', max_digits=4, verbose_name='مصرف سوخت شهری')),
                ('roadFuelUse', models.DecimalField(decimal_places=1, help_text='مصرف سوخت جاده ای برحسب لیتر در هر صد کیلومتر', max_digits=4, verbose_name='مصرف سوخت جاده ای')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('options', models.TextField(verbose_name='امکانات رفاهی و آپشن ها')),
                ('cost', models.BigIntegerField(help_text='قیمت بر حسب تومان', verbose_name='قیمت')),
                ('status', models.CharField(choices=[('موجود', 'موجود'), ('رزرو شده', 'رزرو شده')], default='a', max_length=100, verbose_name='وضعیت')),
                ('mainImage', models.ImageField(upload_to='uploads/cars/', verbose_name='تصویر اصلی')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/cars/', verbose_name='تصویر 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/cars/', verbose_name='تصویر 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/cars/', verbose_name='تصویر 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/cars/', verbose_name='تصویر 4')),
                ('viewsNum', models.IntegerField(default=0, verbose_name='تعداد بازدیدها')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='نام کارخانه سازنده', null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Brand', verbose_name='برند')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Country', verbose_name='کشور سازنده')),
            ],
            options={
                'verbose_name': 'خورو',
                'verbose_name_plural': 'خودروها',
            },
        ),
    ]
