# Generated by Django 2.2.4 on 2019-08-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='yearOfProduction',
            field=models.IntegerField(help_text='مثال: 2019', verbose_name='سال تولید'),
        ),
    ]
