# Generated by Django 2.2.4 on 2019-08-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20190816_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarView',
        ),
    ]
