# Generated by Django 2.2.4 on 2019-08-31 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20190829_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'خودرو', 'verbose_name_plural': 'خودروها'},
        ),
    ]
